version: '2'
volumes:
    resin-data:
services:
  lora:
    build: ./lora/
    privileged: true
    restart: always
  radiosonde:
    build: ./radiosonde/
    privileged: true
    restart: always
    ports:
     - "80:80"
    expose:
      - "80"
    volumes:
      - 'resin-data:/data'
  wpe:
    restart: always
    build: ./wpe
    privileged: true
